"""Add video_hook to banner_tasks

Revision ID: 27a9cc284ff3
Revises: b09ba5e8cf40
Create Date: 2026-04-07 15:24:44.556074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a9cc284ff3'
down_revision: Union[str, Sequence[str], None] = 'b09ba5e8cf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_tasks', sa.Column('video_hook', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner_tasks', 'video_hook')
    # ### end Alembic commands ###
