"""add ugc aspect ratio video url columns to banner_tasks

Revision ID: 8760fc55eaeb
Revises: k3f4a5b6c7d8
Create Date: 2026-04-19 13:34:23.679513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8760fc55eaeb'
down_revision: Union[str, Sequence[str], None] = 'k3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # TEXT avoids MySQL InnoDB row-size errors (65535-byte limit with many existing VARCHAR URL columns).
    op.add_column('banner_tasks', sa.Column('ugc_composited_video_url_1_1', sa.Text(), nullable=True))
    op.add_column('banner_tasks', sa.Column('ugc_final_video_url_1_1', sa.Text(), nullable=True))
    op.add_column('banner_tasks', sa.Column('ugc_composited_video_url_16_9', sa.Text(), nullable=True))
    op.add_column('banner_tasks', sa.Column('ugc_final_video_url_16_9', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner_tasks', 'ugc_final_video_url_16_9')
    op.drop_column('banner_tasks', 'ugc_composited_video_url_16_9')
    op.drop_column('banner_tasks', 'ugc_final_video_url_1_1')
    op.drop_column('banner_tasks', 'ugc_composited_video_url_1_1')
    # ### end Alembic commands ###
