"""Add vertical format columns

Revision ID: b09ba5e8cf40
Revises: 5b8aa1b1152b
Create Date: 2026-04-07 14:25:07.292933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b09ba5e8cf40'
down_revision: Union[str, Sequence[str], None] = '5b8aa1b1152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_tasks', sa.Column('rendered_banner_1_vertical_url', sa.String(length=1024), nullable=True))
    op.add_column('banner_tasks', sa.Column('rendered_banner_2_vertical_url', sa.String(length=1024), nullable=True))
    op.add_column('banner_tasks', sa.Column('video_url_1_vertical', sa.String(length=1024), nullable=True))
    op.add_column('banner_tasks', sa.Column('video_url_2_vertical', sa.String(length=1024), nullable=True))
    op.drop_column('banner_tasks', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_tasks', sa.Column('video_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True))
    op.drop_column('banner_tasks', 'video_url_2_vertical')
    op.drop_column('banner_tasks', 'video_url_1_vertical')
    op.drop_column('banner_tasks', 'rendered_banner_2_vertical_url')
    op.drop_column('banner_tasks', 'rendered_banner_1_vertical_url')
    # ### end Alembic commands ###
